### ISSUE TITLE
all-requires@0.0.4 not being installed

### ISSUE THREAD

**Issue by michaelrhodes** [boo1ean/irm#5]
This is because of semver resolves `0.0.x` values: [semver#caret-ranges](https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4-). I’m not sure if you want to just hardcode the version in the dependencies object, or bump the major or minor version of `all-requires` to make things smoother going forward.

**Comment by boo1ean** [comment]
Merged pr #4, updated `all-requires` version and published
boo1ean/irm@96d78712123a196f5e36fe9c1b11a8ecbe6cf0aa
